from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1462, 833)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("time.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 0, 381, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 60, 251, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 470, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 520, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(870, 520, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 410, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.cb_fuso_origem = QtWidgets.QComboBox(self.centralwidget)
        self.cb_fuso_origem.setGeometry(QtCore.QRect(140, 470, 451, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.cb_fuso_origem.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_fuso_origem.setFont(font)
        self.cb_fuso_origem.setStyleSheet("color: rgb(0, 0, 0)")
        self.cb_fuso_origem.setObjectName("cb_fuso_origem")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")
        self.cb_fuso_origem.addItem("")

        self.cb_hora = QtWidgets.QComboBox(self.centralwidget)
        self.cb_hora.setGeometry(QtCore.QRect(140, 520, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.cb_hora.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cb_hora.setFont(font)
        self.cb_hora.setStyleSheet("color: rgb(0, 0, 0)\n""")
        self.cb_hora.setObjectName("cb_hora")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")
        self.cb_hora.addItem("")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1060, 460, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        self.cb_fuso_destino = QtWidgets.QComboBox(self.centralwidget)
        self.cb_fuso_destino.setGeometry(QtCore.QRect(930, 520, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_fuso_destino.setFont(font)
        self.cb_fuso_destino.setStyleSheet("color: rgb(0, 0, 0)")
        self.cb_fuso_destino.setObjectName("cb_fuso_destino")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")
        self.cb_fuso_destino.addItem("")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(870, 570, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_11.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.le_minuto = QtWidgets.QLineEdit(self.centralwidget)
        self.le_minuto.setGeometry(QtCore.QRect(1080, 570, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)

        self.le_minuto.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_minuto.setFont(font)
        self.le_minuto.setStyleSheet("background-color: rgb(217, 217, 217)")
        self.le_minuto.setText("")
        self.le_minuto.setObjectName("le_minuto")

        self.btn_converter = QtWidgets.QPushButton(self.centralwidget)
        self.btn_converter.setGeometry(QtCore.QRect(730, 700, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_converter.setFont(font)
        self.btn_converter.setStyleSheet("color: rgb(55, 166, 0)")
        self.btn_converter.setObjectName("btn_converter")

        self.btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair.setGeometry(QtCore.QRect(870, 700, 121, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btn_sair.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_sair.setFont(font)
        self.btn_sair.setStyleSheet("color: rgb(0, 0, 0)")
        self.btn_sair.setObjectName("btn_sair")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(210, 520, 71, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.cb_minuto = QtWidgets.QComboBox(self.centralwidget)
        self.cb_minuto.setGeometry(QtCore.QRect(290, 520, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cb_minuto.setFont(font)
        self.cb_minuto.setStyleSheet("color: rgb(0, 0, 0)")
        self.cb_minuto.setObjectName("cb_minuto")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")
        self.cb_minuto.addItem("")

        self.le_hora = QtWidgets.QLineEdit(self.centralwidget)
        self.le_hora.setGeometry(QtCore.QRect(930, 570, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)

        self.le_hora.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_hora.setFont(font)
        self.le_hora.setStyleSheet("background-color: rgb(217, 217, 217)")
        self.le_hora.setText("")
        self.le_hora.setObjectName("le_hora")

        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1000, 570, 71, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_14.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")

        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1110, 620, 47, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_15.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")

        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(870, 620, 41, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_16.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")

        self.le_dia = QtWidgets.QLineEdit(self.centralwidget)
        self.le_dia.setGeometry(QtCore.QRect(920, 620, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.le_dia.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_dia.setFont(font)
        self.le_dia.setStyleSheet("background-color: rgb(217, 217, 217)")
        self.le_dia.setText("")
        self.le_dia.setObjectName("le_dia")

        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(990, 620, 47, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_17.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")

        self.le_mes = QtWidgets.QLineEdit(self.centralwidget)
        self.le_mes.setGeometry(QtCore.QRect(1040, 620, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.le_mes.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_mes.setFont(font)
        self.le_mes.setStyleSheet("background-color: rgb(217, 217, 217)")
        self.le_mes.setText("")
        self.le_mes.setObjectName("le_mes")

        self.le_ano = QtWidgets.QLineEdit(self.centralwidget)
        self.le_ano.setGeometry(QtCore.QRect(1160, 620, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.le_ano.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_ano.setFont(font)
        self.le_ano.setStyleSheet("background-color: rgb(217, 217, 217)")
        self.le_ano.setText("")
        self.le_ano.setObjectName("le_ano")

        self.calendario = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendario.setGeometry(QtCore.QRect(140, 570, 312, 191))
        self.calendario.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\nbackground-color: rgb(55, 166, "
                                      "0);\ncolor: rgb(0, 0, 0);\nselection-background-color:rgb(0, 0, 0);\nselection-"
                                      "color: rgb(55, 166, 0)")
        self.calendario.setObjectName("calendario")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(80, 570, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 166, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 151, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo_ifrn.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(520, 30, 871, 421))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("fuso_horario_mundial.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1462, 21))
        self.menubar.setObjectName("menubar")

        self.menuSobre = QtWidgets.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionSobre_Programa = QtWidgets.QAction(MainWindow)
        self.actionSobre_Programa.setObjectName("actionEquipe")

        self.menuSobre.addAction(self.actionSobre_Programa)

        self.menubar.addAction(self.menuSobre.menuAction())

        # 1 - Lívia
        # Impossibilitar maximização
        Janela_Principal.setCentralWidget(self.centralwidget)
        Janela_Principal.setFixedSize(Janela_Principal.width(), Janela_Principal.height())

        # Chamar funções para converter e mostrar a tela "sobre"
        self.btn_converter.clicked.connect(self.converter)
        self.actionSobre_Programa.triggered.connect(self.chamar_sobre)

        self.retranslateUi(MainWindow)

        self.btn_sair.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def chamar_sobre(self):
        from Conversor_de_Fusos_Sobre import Ui_Sobre
        self.janela = QtWidgets.QMainWindow()
        self.sobre = Ui_Sobre()
        self.sobre.setupUi(self.janela)
        self.janela.show()

    def converter(self):
        # Coleta de dados do usuário
        ano, mes = self.calendario.selectedDate().year(), self.calendario.selectedDate().month()
        ano_bissexto = True if (ano % 4 == 0 and ano % 100 != 0) or (ano % 100 == 0 and ano % 400 == 0) else False
        meses = {'1': 31, '2': 28 if not ano_bissexto else 29, '3': 31, '4': 30, '5': 31, '6': 30, '7': 31, '8': 31,
                 '9': 30, '10': 31, '11': 30, '12': 31}
        quant_dias, dia = meses[str(mes)], self.calendario.selectedDate().day()
        fuso_origem_hora = self.cb_fuso_origem.currentText()[-6:-4]
        fuso_origem_minuto = int(self.cb_fuso_origem.currentText()[-3:-1])
        fuso_destino_hora = self.cb_fuso_destino.currentText()[-6:-4]
        fuso_destino_minuto = int(self.cb_fuso_destino.currentText()[-3:-1])
        sinal_fuso_origem = self.cb_fuso_origem.currentText()[-8]
        sinal_fuso_destino, minuto_entrada = self.cb_fuso_destino.currentText()[-8], int(self.cb_minuto.currentText())
        hora_inicial = int(str(self.cb_hora.currentText()))

        # 2 - Gil
        # Tratamento de dados
        fuso_origem = int(sinal_fuso_origem + fuso_origem_hora)
        fuso_destino, hora_extra = int(sinal_fuso_destino + fuso_destino_hora), 0
        fuso_hora, fuso_minuto = fuso_destino - fuso_origem, fuso_origem_minuto + fuso_destino_minuto

        # Evitar minuto maior que 60
        if fuso_minuto == 30:
            if fuso_minuto + minuto_entrada >= 60:
                if fuso_destino < fuso_origem:
                    hora_extra += 1
                minuto_entrada = fuso_minuto + minuto_entrada - 60
            else:
                if fuso_destino > fuso_origem:
                    hora_extra -= 1
                minuto_entrada += fuso_minuto

        # 3 - Bia
        # Cálculo do fuso
        hora_final = hora_inicial + fuso_hora + hora_extra
        # Evitar hora menor que 0
        while hora_final < 0:
            hora_final += 24
            dia -= 1
            # Evitar dia igual a 0
            if dia == 0:
                dia = meses[str(mes - 1)]
                mes -= 1
                # Evitar mes menor ou igual a 0
                while mes <= 0:
                    mes += 12
                    ano -= 1
        # Evitar hora maior que 24
        while hora_final > 23:
            hora_final -= 24
            dia += 1
            # Evitar dia maior do que o mês permite
            if dia > quant_dias:
                mes += 1
                dia = 1
                # Evitar mês maior que 12
                while mes > 12:
                    mes -= 12
                    ano += 1

        # Setar os lineEdits com os valores finais
        self.le_hora.setText(str(f'0{hora_final}') if hora_final < 10 else str(hora_final))
        self.le_minuto.setText(str(f'0{minuto_entrada}' if minuto_entrada < 10 else str(minuto_entrada)))
        self.le_dia.setText(str(f'0{dia}' if dia < 10 else str(dia)))
        self.le_mes.setText(str(f'0{mes}') if mes < 10 else str(mes))
        self.le_ano.setText(str(f'000{ano}' if ano < 10 else str(f'00{ano}') if ano < 100 else str(f'0{ano}') if
                            ano < 1000 else str(ano)))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Conversor de Fusos"))

        self.label_2.setText(_translate("MainWindow", "Conversor de"))

        self.label_3.setText(_translate("MainWindow", "Fusos"))

        self.label_4.setText(_translate("MainWindow", "Fuso:"))

        self.label_5.setText(_translate("MainWindow", "Hora:"))

        self.label_6.setText(_translate("MainWindow", "Fuso:"))

        self.label_7.setText(_translate("MainWindow", "Origem"))

        self.cb_fuso_origem.setItemText(0, _translate("MainWindow", "Ilha Howland (UTC - 12:00)"))
        self.cb_fuso_origem.setItemText(1, _translate("MainWindow", "Samoa Americana (UTC - 11:00)"))
        self.cb_fuso_origem.setItemText(2, _translate("MainWindow", "Havaí, EUA (UTC - 10:00)"))
        self.cb_fuso_origem.setItemText(3, _translate("MainWindow", "Ilhas Marquesas, Polinésia Francesa (UTC - 09:30)"
                                                      ))
        self.cb_fuso_origem.setItemText(4, _translate("MainWindow", "Alasca, EUA (UTC - 09:00)"))
        self.cb_fuso_origem.setItemText(5, _translate("MainWindow", "Califórnia, EUA (UTC - 08:00)"))
        self.cb_fuso_origem.setItemText(6, _translate("MainWindow", "Arizona, EUA (UTC - 07:00)"))
        self.cb_fuso_origem.setItemText(7, _translate("MainWindow", "Texas, EUA (UTC - 06:00)"))
        self.cb_fuso_origem.setItemText(8, _translate("MainWindow", "Colômbia (UTC - 05:00)"))
        self.cb_fuso_origem.setItemText(9, _translate("MainWindow", "Venezuela (UTC - 04:00)"))
        self.cb_fuso_origem.setItemText(10, _translate("MainWindow", "Terra Nova, Canadá (UTC - 03:30)"))
        self.cb_fuso_origem.setItemText(11, _translate("MainWindow", "São Paulo, Brasil (UTC - 03:00)"))
        self.cb_fuso_origem.setItemText(12, _translate("MainWindow", "Fernando de Noronha, Brasil (UTC - 02:00)"))
        self.cb_fuso_origem.setItemText(13, _translate("MainWindow", "Cabo Verde (UTC - 01:00)"))
        self.cb_fuso_origem.setItemText(14, _translate("MainWindow", "Marrocos (UTC + 00:00)"))
        self.cb_fuso_origem.setItemText(15, _translate("MainWindow", "Nigéria (UTC + 01:00)"))
        self.cb_fuso_origem.setItemText(16, _translate("MainWindow", "Turquia (UTC + 02:00)"))
        self.cb_fuso_origem.setItemText(17, _translate("MainWindow", "Rússia (UTC + 03:00)"))
        self.cb_fuso_origem.setItemText(18, _translate("MainWindow", "Irã (UTC + 03:30)"))
        self.cb_fuso_origem.setItemText(19, _translate("MainWindow", "Emirados Árabes Unidos (UTC + 04:00)"))
        self.cb_fuso_origem.setItemText(20, _translate("MainWindow", "Afeganistão (UTC + 04:30)"))
        self.cb_fuso_origem.setItemText(21, _translate("MainWindow", "Paquistão (UTC + 05:00)"))
        self.cb_fuso_origem.setItemText(22, _translate("MainWindow", "Índia (UTC + 05:30)"))
        self.cb_fuso_origem.setItemText(23, _translate("MainWindow", "Cazaquistão (UTC + 06:00)"))
        self.cb_fuso_origem.setItemText(24, _translate("MainWindow", "Indonésia (UTC + 07:00)"))
        self.cb_fuso_origem.setItemText(25, _translate("MainWindow", "República Popular da China (UTC + 08:00)"))
        self.cb_fuso_origem.setItemText(26, _translate("MainWindow", "Japão (UTC + 09:00)"))
        self.cb_fuso_origem.setItemText(27, _translate("MainWindow", "Papua Nova Guiné (UTC + 10:00)"))
        self.cb_fuso_origem.setItemText(28, _translate("MainWindow", "Ilhas Salomão (UTC + 11:00)"))
        self.cb_fuso_origem.setItemText(29, _translate("MainWindow", "Fiji (UTC + 12:00)"))

        self.cb_hora.setItemText(0, _translate("MainWindow", "00"))
        self.cb_hora.setItemText(1, _translate("MainWindow", "01"))
        self.cb_hora.setItemText(2, _translate("MainWindow", "02"))
        self.cb_hora.setItemText(3, _translate("MainWindow", "03"))
        self.cb_hora.setItemText(4, _translate("MainWindow", "04"))
        self.cb_hora.setItemText(5, _translate("MainWindow", "05"))
        self.cb_hora.setItemText(6, _translate("MainWindow", "06"))
        self.cb_hora.setItemText(7, _translate("MainWindow", "07"))
        self.cb_hora.setItemText(8, _translate("MainWindow", "08"))
        self.cb_hora.setItemText(9, _translate("MainWindow", "09"))
        self.cb_hora.setItemText(10, _translate("MainWindow", "10"))
        self.cb_hora.setItemText(11, _translate("MainWindow", "11"))
        self.cb_hora.setItemText(12, _translate("MainWindow", "12"))
        self.cb_hora.setItemText(13, _translate("MainWindow", "13"))
        self.cb_hora.setItemText(14, _translate("MainWindow", "14"))
        self.cb_hora.setItemText(15, _translate("MainWindow", "15"))
        self.cb_hora.setItemText(16, _translate("MainWindow", "16"))
        self.cb_hora.setItemText(17, _translate("MainWindow", "17"))
        self.cb_hora.setItemText(18, _translate("MainWindow", "18"))
        self.cb_hora.setItemText(19, _translate("MainWindow", "19"))
        self.cb_hora.setItemText(20, _translate("MainWindow", "20"))
        self.cb_hora.setItemText(21, _translate("MainWindow", "21"))
        self.cb_hora.setItemText(22, _translate("MainWindow", "22"))
        self.cb_hora.setItemText(23, _translate("MainWindow", "23"))

        self.label_10.setText(_translate("MainWindow", "Destino"))

        self.cb_fuso_destino.setItemText(0, _translate("MainWindow", "Ilha Howland (UTC - 12:00)"))
        self.cb_fuso_destino.setItemText(1, _translate("MainWindow", "Samoa Americana (UTC - 11:00)"))
        self.cb_fuso_destino.setItemText(2, _translate("MainWindow", "Havaí, EUA (UTC - 10:00)"))
        self.cb_fuso_destino.setItemText(3, _translate("MainWindow", "Ilhas Marquesas, Polinésia Francesa (UTC - 09:30)"
                                                       ))
        self.cb_fuso_destino.setItemText(4, _translate("MainWindow", "Alasca, EUA (UTC - 09:00)"))
        self.cb_fuso_destino.setItemText(5, _translate("MainWindow", "Califórnia, EUA (UTC - 08:00)"))
        self.cb_fuso_destino.setItemText(6, _translate("MainWindow", "Arizona, EUA (UTC - 07:00)"))
        self.cb_fuso_destino.setItemText(7, _translate("MainWindow", "Texas, EUA (UTC - 06:00)"))
        self.cb_fuso_destino.setItemText(8, _translate("MainWindow", "Colômbia (UTC - 05:00)"))
        self.cb_fuso_destino.setItemText(9, _translate("MainWindow", "Venezuela (UTC - 04:00)"))
        self.cb_fuso_destino.setItemText(10, _translate("MainWindow", "Terra Nova, Canadá (UTC - 03:30)"))
        self.cb_fuso_destino.setItemText(11, _translate("MainWindow", "São Paulo, Brasil (UTC - 03:00)"))
        self.cb_fuso_destino.setItemText(12, _translate("MainWindow", "Fernando de Noronha, Brasil (UTC - 02:00)"))
        self.cb_fuso_destino.setItemText(13, _translate("MainWindow", "Cabo Verde (UTC - 01:00)"))
        self.cb_fuso_destino.setItemText(14, _translate("MainWindow", "Marrocos (UTC + 00:00)"))
        self.cb_fuso_destino.setItemText(15, _translate("MainWindow", "Nigéria (UTC + 01:00)"))
        self.cb_fuso_destino.setItemText(16, _translate("MainWindow", "Turquia (UTC + 02:00)"))
        self.cb_fuso_destino.setItemText(17, _translate("MainWindow", "Rússia (UTC + 03:00)"))
        self.cb_fuso_destino.setItemText(18, _translate("MainWindow", "Irã (UTC + 03:30)"))
        self.cb_fuso_destino.setItemText(19, _translate("MainWindow", "Emirados Árabes Unidos (UTC + 04:00)"))
        self.cb_fuso_destino.setItemText(20, _translate("MainWindow", "Afeganistão (UTC + 04:30)"))
        self.cb_fuso_destino.setItemText(21, _translate("MainWindow", "Paquistão (UTC + 05:00)"))
        self.cb_fuso_destino.setItemText(22, _translate("MainWindow", "Índia (UTC + 05:30)"))
        self.cb_fuso_destino.setItemText(23, _translate("MainWindow", "Cazaquistão (UTC + 06:00)"))
        self.cb_fuso_destino.setItemText(24, _translate("MainWindow", "Indonésia (UTC + 07:00)"))
        self.cb_fuso_destino.setItemText(25, _translate("MainWindow", "República Popular da China (UTC + 08:00)"))
        self.cb_fuso_destino.setItemText(26, _translate("MainWindow", "Japão (UTC + 09:00)"))
        self.cb_fuso_destino.setItemText(27, _translate("MainWindow", "Papua Nova Guiné (UTC + 10:00)"))
        self.cb_fuso_destino.setItemText(28, _translate("MainWindow", "Ilhas Salomão (UTC + 11:00)"))
        self.cb_fuso_destino.setItemText(29, _translate("MainWindow", "Fiji (UTC + 12:00)"))

        self.label_11.setText(_translate("MainWindow", "Hora:"))

        self.btn_converter.setToolTip(_translate("MainWindow", "Enter"))
        self.btn_converter.setStatusTip(_translate("MainWindow", "Enter"))
        self.btn_converter.setText(_translate("MainWindow", "Converter"))
        self.btn_converter.setShortcut(_translate("MainWindow", "Return"))

        self.btn_sair.setToolTip(_translate("MainWindow", "Esc"))
        self.btn_sair.setStatusTip(_translate("MainWindow", "Esc"))
        self.btn_sair.setText(_translate("MainWindow", "Sair"))
        self.btn_sair.setShortcut(_translate("MainWindow", "Esc"))

        self.label_8.setText(_translate("MainWindow", "Minuto:"))

        self.cb_minuto.setItemText(0, _translate("MainWindow", "00"))
        self.cb_minuto.setItemText(1, _translate("MainWindow", "01"))
        self.cb_minuto.setItemText(2, _translate("MainWindow", "02"))
        self.cb_minuto.setItemText(3, _translate("MainWindow", "03"))
        self.cb_minuto.setItemText(4, _translate("MainWindow", "04"))
        self.cb_minuto.setItemText(5, _translate("MainWindow", "05"))
        self.cb_minuto.setItemText(6, _translate("MainWindow", "06"))
        self.cb_minuto.setItemText(7, _translate("MainWindow", "07"))
        self.cb_minuto.setItemText(8, _translate("MainWindow", "08"))
        self.cb_minuto.setItemText(9, _translate("MainWindow", "09"))
        self.cb_minuto.setItemText(10, _translate("MainWindow", "10"))
        self.cb_minuto.setItemText(11, _translate("MainWindow", "11"))
        self.cb_minuto.setItemText(12, _translate("MainWindow", "12"))
        self.cb_minuto.setItemText(13, _translate("MainWindow", "13"))
        self.cb_minuto.setItemText(14, _translate("MainWindow", "14"))
        self.cb_minuto.setItemText(15, _translate("MainWindow", "15"))
        self.cb_minuto.setItemText(16, _translate("MainWindow", "16"))
        self.cb_minuto.setItemText(17, _translate("MainWindow", "17"))
        self.cb_minuto.setItemText(18, _translate("MainWindow", "18"))
        self.cb_minuto.setItemText(19, _translate("MainWindow", "19"))
        self.cb_minuto.setItemText(20, _translate("MainWindow", "20"))
        self.cb_minuto.setItemText(21, _translate("MainWindow", "21"))
        self.cb_minuto.setItemText(22, _translate("MainWindow", "22"))
        self.cb_minuto.setItemText(23, _translate("MainWindow", "23"))
        self.cb_minuto.setItemText(24, _translate("MainWindow", "24"))
        self.cb_minuto.setItemText(25, _translate("MainWindow", "25"))
        self.cb_minuto.setItemText(26, _translate("MainWindow", "26"))
        self.cb_minuto.setItemText(27, _translate("MainWindow", "27"))
        self.cb_minuto.setItemText(28, _translate("MainWindow", "28"))
        self.cb_minuto.setItemText(29, _translate("MainWindow", "29"))
        self.cb_minuto.setItemText(30, _translate("MainWindow", "30"))
        self.cb_minuto.setItemText(31, _translate("MainWindow", "31"))
        self.cb_minuto.setItemText(32, _translate("MainWindow", "32"))
        self.cb_minuto.setItemText(33, _translate("MainWindow", "33"))
        self.cb_minuto.setItemText(34, _translate("MainWindow", "34"))
        self.cb_minuto.setItemText(35, _translate("MainWindow", "35"))
        self.cb_minuto.setItemText(36, _translate("MainWindow", "36"))
        self.cb_minuto.setItemText(37, _translate("MainWindow", "37"))
        self.cb_minuto.setItemText(38, _translate("MainWindow", "38"))
        self.cb_minuto.setItemText(39, _translate("MainWindow", "39"))
        self.cb_minuto.setItemText(40, _translate("MainWindow", "40"))
        self.cb_minuto.setItemText(41, _translate("MainWindow", "41"))
        self.cb_minuto.setItemText(42, _translate("MainWindow", "42"))
        self.cb_minuto.setItemText(43, _translate("MainWindow", "43"))
        self.cb_minuto.setItemText(44, _translate("MainWindow", "44"))
        self.cb_minuto.setItemText(45, _translate("MainWindow", "45"))
        self.cb_minuto.setItemText(46, _translate("MainWindow", "46"))
        self.cb_minuto.setItemText(47, _translate("MainWindow", "47"))
        self.cb_minuto.setItemText(48, _translate("MainWindow", "48"))
        self.cb_minuto.setItemText(49, _translate("MainWindow", "49"))
        self.cb_minuto.setItemText(50, _translate("MainWindow", "50"))
        self.cb_minuto.setItemText(51, _translate("MainWindow", "51"))
        self.cb_minuto.setItemText(52, _translate("MainWindow", "52"))
        self.cb_minuto.setItemText(53, _translate("MainWindow", "53"))
        self.cb_minuto.setItemText(54, _translate("MainWindow", "54"))
        self.cb_minuto.setItemText(55, _translate("MainWindow", "55"))
        self.cb_minuto.setItemText(56, _translate("MainWindow", "56"))
        self.cb_minuto.setItemText(57, _translate("MainWindow", "57"))
        self.cb_minuto.setItemText(58, _translate("MainWindow", "58"))
        self.cb_minuto.setItemText(59, _translate("MainWindow", "59"))

        self.label_14.setText(_translate("MainWindow", "Minuto:"))

        self.label_15.setText(_translate("MainWindow", "Ano:"))

        self.label_16.setText(_translate("MainWindow", "Dia:"))

        self.label_17.setText(_translate("MainWindow", "Mês:"))

        self.label_9.setText(_translate("MainWindow", "Data:"))

        self.menuSobre.setTitle(_translate("MainWindow", "Sobre"))

        self.actionSobre_Programa.setText(_translate("MainWindow", "Sobre o Programa"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    Janela_Principal = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Janela_Principal)
    Janela_Principal.show()
    sys.exit(app.exec_())
